WITH Car_Rental_Count AS (
    -- 1. 2022년 8월~10월 동안 총 대여 횟수가 5회 이상인 자동차 찾기
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)

-- 2. 위에서 찾은 자동차들의 월별 대여 횟수 구하기
SELECT 
    MONTH(START_DATE) AS MONTH, 
    CAR_ID, 
    COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM Car_Rental_Count)  -- 5회 이상 대여된 자동차만 필터링
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'  -- 2022년 8월~10월 데이터만 포함
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;
